### ISSUE TITLE
Notice 페이지의 adminntc 라우트 수정시 이슈

### ISSUE THREAD

**Issue by allzeroyou** [DSLikelion10/LIKEFEST-frontend#66]
총학에서 공지사항을 남기는 adminntc 라우트에서 수정 시
1. 태그 변경시 적용되지 않음
2. 수정한 글의 마지막 한 문자가 잘리는 현상

**Comment by eunbeann** [comment]
이 두 가지 모두 동일한 렌더링 과정 문제였습니다~!
해결 완~!! 

![image](https://user-images.githubusercontent.com/65286685/167520334-cb747b4c-05a3-49f8-9883-ed6cbc9d7996.png)
