### ISSUE TITLE
햄버거메뉴, Header, Content 관련하여

### ISSUE THREAD

**Issue by Chanran33** [DSLikelion10/LIKEFEST-frontend#8]
**햄버거메뉴**
![image](https://user-images.githubusercontent.com/49816869/163669456-001c8952-bfc0-44c7-ba78-6880ab219908.png)
![image](https://user-images.githubusercontent.com/49816869/163669476-487b97dc-72b8-480d-acbf-3e4ba11bca57.png)
보통이런식으로 햄버거 메뉴 내려올 때 Content위로 오는 형식인데 저희는 Content영역이 햄버거 메뉴 아래로 밀려서 이 부분 구체적으로 어떻게 처리할지 이야기 나온게 있나요?

**Header, Content**
현재 수정님이 적용해 주신 Content영역은 Header를 제외한 영역 같은데
위의 Header처리가 없어서 이 부분은 추후 추가로 알고 Header제외한 영역 개발진행하면 될까요?
![image](https://user-images.githubusercontent.com/49816869/163669575-2697d15c-c7ee-427f-9cd9-3fbd482b1257.png)

**Comment by soosoo030** [comment]
**햄버거 메뉴**
  => 일부러 Content 영역의 내용을 가리지 않도록 구현한 것이었는데 디자이너 분에게 상의해보겠습니다!

**Header,Content**
  => 헤더 디자인 자체는 동일해서 메뉴바에서 넣어 가는게 좋을 것 같긴 한데 페이지마다 내용이 달라지는 것 때문에 Content 영역 안에 Header를 넣는 것으로 처음엔 생각했습니다! 한 번 시도해보고 안 되겠다 싶으면 Content 영역 안에 넣는 걸로 할게요! 우선은 Header 제외한 영역 개발 진행해주세요:D
